name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.x"
  SOLUTION_FILE: "DevHabit.sln"

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: .
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
          
      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build solution
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ${{ env.SOLUTION_FILE }} --configuration Release --no-restore --no-build

      - name: Publish artifacts
        run: dotnet publish ${{ env.SOLUTION_FILE }} --configuration Release --no-restore --no-build
